import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, router } from 'expo-router';
import { AppButton } from '@/src/components/AppButton';
import { AppInput } from '@/src/components/AppInput';
import { useAuth } from '@/src/context/AuthContext';
import { colors } from '@/src/theme/colors';

export default function LoginScreen() {
  const { signIn } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit() { setLoading(true); setError(''); try { await signIn(email, password); router.replace('/(tabs)'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to sign in.'); } finally { setLoading(false); } }
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.top}><Text style={styles.back}>‹</Text><View><Text style={styles.eyebrow}>Sign in as</Text><Text style={styles.heading}>Driver</Text></View><Text style={styles.moon}>☾</Text></View><View style={styles.mark}><Text style={styles.markText}>BP</Text></View><Text style={styles.driverLabel}>Driver Login</Text><View style={styles.form}><AppInput label="Mobile Number or Email" value={email} onChangeText={setEmail} placeholder="09XX-XXX-XXXX" autoCapitalize="none" /><AppInput label="Password" value={password} onChangeText={setPassword} placeholder="Enter password" secureTextEntry />{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={styles.forgot}>Forgot Password?</Text><AppButton title="Sign In" onPress={submit} loading={loading} /></View><View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>or continue with</Text><View style={styles.line} /></View><View style={styles.social}><AppButton title="G  Google" onPress={() => {}} variant="secondary" /><AppButton title="f  Facebook" onPress={() => {}} variant="secondary" /></View><Text style={styles.signup}>Don't have an account? <Link href={'/(auth)/register' as never} style={styles.orange}>Sign Up</Link></Text></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { flexGrow: 1, padding: 23, paddingTop: 32 }, top: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.surface, textAlign: 'center', fontSize: 24, lineHeight: 26, color: colors.text }, eyebrow: { color: colors.muted, fontSize: 12 }, heading: { color: colors.text, fontSize: 18, fontWeight: '800' }, moon: { marginLeft: 'auto', backgroundColor: colors.surface, borderRadius: 16, padding: 7, color: colors.navy }, mark: { alignSelf: 'center', marginTop: 48, width: 62, height: 62, borderRadius: 18, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, markText: { color: '#fff', fontSize: 24, fontWeight: '900' }, driverLabel: { textAlign: 'center', color: colors.brand, fontWeight: '800', marginTop: 12 }, form: { marginTop: 34, backgroundColor: colors.surface, borderRadius: 16, padding: 17, gap: 13 }, error: { color: colors.danger, fontSize: 12 }, forgot: { color: colors.brand, textAlign: 'right', fontSize: 12, fontWeight: '700' }, divider: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 18 }, line: { flex: 1, height: 1, backgroundColor: colors.border }, or: { color: colors.muted, fontSize: 12 }, social: { flexDirection: 'row', gap: 10 }, signup: { textAlign: 'center', color: colors.muted, marginTop: 17, fontSize: 13 }, orange: { color: colors.brand, fontWeight: '800' } });
