import { useEffect, useState } from 'react';
import { Activity, Car, DollarSign, RefreshCw, Users } from 'lucide-react';
import { apiFetch } from '../../lib/api';
import StatusBadge from '../ui/StatusBadge';

export default function OverviewPanel({ onAuthError }) {
  const [data, setData] = useState({ trips: [], drivers: [], customers: 0 }); const [loading, setLoading] = useState(true);
  async function load() { try { setLoading(true); const [tripsResponse, driversResponse, usersResponse] = await Promise.all([apiFetch('/api/trips/history?page=1&pageSize=50'), apiFetch('/api/drivers?pageSize=50'), apiFetch('/api/users?role=customer&pageSize=1')]); if ([tripsResponse, driversResponse, usersResponse].some(response => response.status === 401 || response.status === 403)) { onAuthError?.(); return; } const trips = tripsResponse.ok ? (await tripsResponse.json()).items || [] : []; const drivers = driversResponse.ok ? (await driversResponse.json()).items || [] : []; const customers = usersResponse.ok ? (await usersResponse.json()).totalCount || 0 : 0; setData({ trips, drivers, customers }); } catch (error) { if (error.isAuthError) onAuthError?.(); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const revenue = data.trips.reduce((sum, trip) => sum + Number(trip.fareAmount || 0), 0); const online = data.drivers.filter(driver => driver.status === 'available').length;
  return <div className="space-y-6"><header className="flex justify-between"><div><h1 className="text-2xl font-bold">Dashboard</h1><p className="text-slate-400 text-sm mt-1">Operations overview from current API records</p></div><button type="button" onClick={load} className="flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-amber-500"><RefreshCw className="w-4 h-4" /> Refresh</button></header>{loading ? <p className="text-amber-500 text-sm font-semibold">Loading operations...</p> : <><div className="grid grid-cols-4 gap-4"><Metric icon={Activity} label="Loaded rides" value={data.trips.length} /><Metric icon={DollarSign} label="Loaded revenue" value={`₱${revenue.toFixed(2)}`} /><Metric icon={Car} label="Available drivers" value={online} /><Metric icon={Users} label="Customers" value={data.customers} /></div><div className="grid grid-cols-3 gap-5"><div className="col-span-2 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-800"><h2 className="font-bold">Recent rides</h2><p className="text-xs text-slate-500 mt-1">Reference screenshots are not used as live data.</p></div><div className="divide-y divide-slate-800/60">{data.trips.slice(0, 6).map(trip => <div key={trip.id} className="p-4 grid grid-cols-5 gap-3 items-center text-sm"><span className="font-semibold">{trip.customerName || 'Passenger'}</span><span className="col-span-2 text-slate-400 truncate">{trip.pickupAddress} → {trip.dropoffAddress}</span><span className="text-amber-400 font-semibold">₱{trip.fareAmount}</span><StatusBadge status={trip.status} /></div>)}{!data.trips.length && <p className="p-6 text-slate-500">No ride records yet.</p>}</div></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><h2 className="font-bold">System status</h2><div className="mt-5 space-y-4 text-sm"><StatusRow label="API Server" value="Operational" /><StatusRow label="Database" value="Connected" /><StatusRow label="Real-time" value="SignalR ready" /><StatusRow label="Maps" value="Leaflet / OSM" /></div></div></div></>}</div>;
}
function Metric({ icon: Icon, label, value }) { return <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><Icon className="w-5 h-5 text-amber-500 mb-3" /><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>; }
function StatusRow({ label, value }) { return <div className="flex justify-between border-b border-slate-800 pb-3"><span className="text-slate-400">{label}</span><span className="text-emerald-400 font-semibold text-xs">{value}</span></div>; }
