import { useEffect, useState } from 'react';
import { RefreshCw, Search, Users } from 'lucide-react';
import { apiFetch } from '../../lib/api';
import StatusBadge from '../ui/StatusBadge';

export default function UsersPanel({ onAuthError }) {
  const [role, setRole] = useState('driver'); const [users, setUsers] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function loadUsers() { try { setLoading(true); setError(''); const response = await apiFetch(`/api/users?role=${role}&pageSize=50`); if (!response.ok) throw new Error('Unable to load users.'); const data = await response.json(); setUsers(data.items || []); } catch (err) { if (err.isAuthError) onAuthError?.(); else setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { loadUsers(); }, [role]);
  const filtered = users.filter(user => `${user.fullName} ${user.email} ${user.phone}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-5"><header className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">User Management</h1><p className="text-slate-400 text-sm mt-1">Live records from the shared users database.</p></div><button type="button" onClick={loadUsers} className="flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-amber-500"><RefreshCw className="w-4 h-4" /> Refresh</button></header><div className="flex items-center justify-between gap-4"><div className="flex rounded-xl bg-slate-900 border border-slate-800 p-1"><button type="button" onClick={() => setRole('driver')} className={`px-4 py-2 rounded-lg text-sm font-semibold ${role === 'driver' ? 'bg-amber-500 text-slate-950' : 'text-slate-400'}`}>Drivers</button><button type="button" onClick={() => setRole('customer')} className={`px-4 py-2 rounded-lg text-sm font-semibold ${role === 'customer' ? 'bg-amber-500 text-slate-950' : 'text-slate-400'}`}>Customers</button></div><label className="flex items-center gap-2 bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-slate-400"><Search className="w-4 h-4" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search name, email, or phone" className="bg-transparent outline-none text-sm text-slate-100 w-64" /></label></div>{error && <p className="text-sm text-red-400">{error}</p>}{loading ? <p className="text-amber-500 text-sm font-semibold">Loading users...</p> : <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-950/40 text-slate-400"><tr><th className="p-4">User</th><th className="p-4">Contact</th><th className="p-4">Status</th><th className="p-4">Joined</th></tr></thead><tbody className="divide-y divide-slate-800/60">{filtered.map(user => <tr key={user.id} className="hover:bg-slate-800/20"><td className="p-4"><div className="flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-amber-500/15 text-amber-400 flex items-center justify-center font-bold"><Users className="w-4 h-4" /></span><div><p className="font-semibold">{user.fullName}</p><p className="text-xs text-slate-500">{user.role}</p></div></div></td><td className="p-4 text-slate-400">{user.phone}<br />{user.email}</td><td className="p-4"><StatusBadge status={user.isActive ? 'available' : 'cancelled'} /></td><td className="p-4 text-slate-400">{new Date(user.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-slate-500">No matching users.</p>}</div>}</div>;
}
