import { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MapPreview } from '@/src/components/MapPreview';
import { api } from '@/src/lib/api';
import { useAuth } from '@/src/context/AuthContext';
import { colors } from '@/src/theme/colors';
const activeStatuses = new Set(['accepted', 'en_route', 'arrived', 'in_progress']);
export default function ActiveScreen() { const { session } = useAuth(); const [trip, setTrip] = useState<any>(null); const [loading, setLoading] = useState(true); useEffect(() => { if (!session?.accessToken) return; api.getHistory(session.accessToken).then(result => setTrip((result.items || []).find((item: any) => activeStatuses.has(item.status)) || null)).catch(() => setTrip(null)).finally(() => setLoading(false)); }, [session?.accessToken]); return <ScrollView style={styles.page} contentContainerStyle={styles.content}><MapPreview compact />{loading ? <View style={styles.empty}><ActivityIndicator color={colors.brand} /></View> : !trip ? <View style={styles.empty}><Text style={styles.emptyTitle}>No active ride</Text><Text style={styles.muted}>Accepted customer bookings will appear here.</Text></View> : <View style={styles.card}><Text style={styles.step}>{trip.status.replace('_', ' ')}</Text><Text style={styles.name}>{trip.customerName || 'Customer'}</Text><View style={styles.route}><Text><Text style={styles.green}>●</Text> {trip.pickupAddress}</Text><Text><Text style={styles.orange}>●</Text> {trip.dropoffAddress}</Text></View><Text style={styles.fare}>P{Number(trip.fareAmount || 0).toFixed(2)}</Text></View>}</ScrollView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { paddingBottom: 24 }, empty: { alignItems: 'center', justifyContent: 'center', padding: 34, gap: 8 }, emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '800' }, muted: { color: colors.muted, fontSize: 12 }, card: { backgroundColor: colors.surface, borderRadius: 15, borderWidth: 1, borderColor: colors.border, margin: 18, padding: 16 }, step: { color: colors.brand, fontWeight: '800', textTransform: 'capitalize', marginBottom: 10 }, name: { color: colors.text, fontWeight: '800', fontSize: 16 }, route: { backgroundColor: '#F8F9FA', borderRadius: 10, padding: 12, gap: 9, marginVertical: 15 }, green: { color: colors.success }, orange: { color: colors.brand }, fare: { color: colors.brand, fontWeight: '900', fontSize: 17 } });
