import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { MapPreview } from '@/src/components/MapPreview';
import { colors } from '@/src/theme/colors';

type Request = { initials: string; name: string; vehicle: string; distance: string; fare: string; from: string; to: string };
const requests: Request[] = [{ initials: 'MS', name: 'Maria Santos', vehicle: 'Tricycle · 2.1 km', distance: '+2 min away', fare: 'P15', from: 'JRMSU Campus', to: 'City Hall' }, { initials: 'PB', name: 'Pedro Bautista', vehicle: 'Tricycle · 4.5 km', distance: '+5 min away', fare: 'P20', from: 'Cawa Cawa Beach', to: 'Rizal Shrine' }];
function RequestCard({ request }: { request: Request }) { const [accepted, setAccepted] = useState(false); return <View style={styles.card}><View style={styles.customer}><View style={styles.avatar}><Text style={styles.initials}>{request.initials}</Text></View><View style={styles.customerCopy}><Text style={styles.name}>{request.name}</Text><Text style={styles.meta}>{request.vehicle}</Text></View><View><Text style={styles.fare}>{request.fare}</Text><Text style={styles.meta}>{request.distance}</Text></View></View><View style={styles.route}><Text><Text style={styles.green}>●</Text>  {request.from}</Text><Text><Text style={styles.orange}>●</Text>  {request.to}</Text></View><View style={styles.actions}><View style={styles.decline}><Text style={styles.declineText}>Decline</Text></View><View style={styles.accept} onTouchEnd={() => setAccepted(true)}><Text style={styles.acceptText}>{accepted ? 'Accepted' : 'Accept Ride'}</Text></View></View></View>; }
export default function HomeScreen() { return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.greeting}>Good afternoon</Text><Text style={styles.title}>Rodel Mangubat</Text></View><View style={styles.online}><Text style={styles.onlineDot}>●</Text><Text style={styles.onlineText}>Online</Text></View></View><View style={styles.stats}><View><Text style={styles.statValue}>8</Text><Text style={styles.statLabel}>Trips Today</Text></View><View><Text style={styles.statValue}>P1,850</Text><Text style={styles.statLabel}>Earnings</Text></View><View><Text style={styles.statValue}>4.9</Text><Text style={styles.statLabel}>Rating</Text></View></View><MapPreview /><Text style={styles.sectionTitle}>Incoming Requests <Text style={styles.count}>2</Text></Text>{requests.map(request => <RequestCard request={request} key={request.name} />)}</ScrollView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { paddingBottom: 24 }, header: { padding: 18, paddingTop: 25, backgroundColor: colors.brand, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, greeting: { color: '#FFE7D9', fontSize: 12 }, title: { color: '#fff', fontSize: 19, fontWeight: '900', marginTop: 4 }, online: { backgroundColor: '#FF8A4C', borderRadius: 18, paddingHorizontal: 11, paddingVertical: 8, flexDirection: 'row', gap: 5 }, onlineDot: { color: '#D1FADF', fontSize: 11 }, onlineText: { color: '#fff', fontWeight: '800', fontSize: 12 }, stats: { backgroundColor: colors.brand, flexDirection: 'row', justifyContent: 'space-around', paddingBottom: 16 }, statValue: { color: '#fff', textAlign: 'center', fontSize: 16, fontWeight: '900' }, statLabel: { color: '#FFE7D9', fontSize: 11, marginTop: 3 }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '900', marginHorizontal: 18, marginTop: 17, marginBottom: 9 }, count: { backgroundColor: colors.brand, color: '#fff', fontSize: 11, paddingHorizontal: 7, borderRadius: 10 }, card: { backgroundColor: colors.surface, borderRadius: 15, borderWidth: 1, borderColor: colors.border, marginHorizontal: 18, marginBottom: 12, padding: 14 }, customer: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 38, height: 38, borderRadius: 10, backgroundColor: '#DDF5FF', alignItems: 'center', justifyContent: 'center' }, initials: { color: '#087EA4', fontWeight: '900' }, customerCopy: { flex: 1, marginLeft: 10 }, name: { color: colors.text, fontWeight: '800', fontSize: 14 }, meta: { color: colors.muted, fontSize: 11, marginTop: 3 }, fare: { color: colors.brand, fontWeight: '900', fontSize: 16, textAlign: 'right' }, route: { backgroundColor: '#F8F9FA', borderRadius: 10, padding: 10, gap: 8, marginVertical: 11 }, green: { color: colors.success }, orange: { color: colors.brand }, actions: { flexDirection: 'row', gap: 8 }, decline: { flex: 1, backgroundColor: '#F2F4F7', borderRadius: 10, minHeight: 42, alignItems: 'center', justifyContent: 'center' }, declineText: { color: colors.muted, fontWeight: '800' }, accept: { flex: 1.15, backgroundColor: colors.brand, borderRadius: 10, minHeight: 42, alignItems: 'center', justifyContent: 'center' }, acceptText: { color: '#fff', fontWeight: '800' } });
