import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MapPreview } from '@/src/components/MapPreview';
import { api } from '@/src/lib/api';
import { useAuth } from '@/src/context/AuthContext';
import { colors } from '@/src/theme/colors';

export default function LiveHomeScreen() {
  const { session } = useAuth();
  const [profile, setProfile] = useState<any>(null); const [requests, setRequests] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [available, setAvailable] = useState(false); const [error, setError] = useState('');
  async function load() { if (!session?.accessToken) return; try { setLoading(true); const [nextProfile, nextRequests, earnings] = await Promise.all([api.getProfile(session.accessToken), api.getRequests(session.accessToken), api.getEarnings(session.accessToken)]); setProfile({ ...nextProfile, earnings }); setRequests(nextRequests); setAvailable(nextProfile.status === 'available'); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load driver data.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [session?.accessToken]);
  async function toggleAvailability() { if (!session?.accessToken) return; try { await api.setAvailability(session.accessToken, !available); setAvailable(!available); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to change availability.'); } }
  async function accept(id: string) { if (!session?.accessToken) return; try { await api.acceptTrip(session.accessToken, id); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Ride is no longer available.'); } }
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.greeting}>Driver dashboard</Text><Text style={styles.title}>{profile?.fullName || session?.fullName || 'Driver'}</Text></View><Pressable onPress={toggleAvailability} style={styles.online}><Text style={styles.onlineDot}>●</Text><Text style={styles.onlineText}>{available ? 'Online' : 'Offline'}</Text></Pressable></View><View style={styles.stats}><Stat value={String(profile?.totalTrips ?? 0)} label="Trips" /><Stat value={`P${Number(profile?.rating ?? 0).toFixed(1)}`} label="Rating" /><Stat value={`P${Number(profile?.earnings?.totalEarnings ?? 0).toFixed(2)}`} label="Earnings" /></View><MapPreview />{loading ? <View style={styles.empty}><ActivityIndicator color={colors.brand} /><Text style={styles.muted}>Loading live requests...</Text></View> : <><Text style={styles.sectionTitle}>Incoming Requests <Text style={styles.count}>{requests.length}</Text></Text>{error ? <Text style={styles.error}>{error}</Text> : null}{requests.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No incoming rides</Text><Text style={styles.muted}>{available ? 'New customer bookings will appear here.' : 'Go online to receive ride requests.'}</Text></View> : requests.map(request => <RequestCard key={request.id} request={request} onAccept={() => accept(request.id)} />)}</>}</ScrollView>;
}
function Stat({ value, label }: { value: string; label: string }) { return <View><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function RequestCard({ request, onAccept }: { request: any; onAccept: () => void }) { return <View style={styles.card}><Text style={styles.name}>{request.customerName || 'Customer'}</Text><Text style={styles.meta}>Requested {new Date(request.requestedAt).toLocaleTimeString()}</Text><View style={styles.route}><Text><Text style={styles.green}>●</Text> {request.pickupAddress}</Text><Text><Text style={styles.orange}>●</Text> {request.dropoffAddress}</Text></View><Text style={styles.fare}>P{Number(request.fareAmount || 0).toFixed(2)}</Text><Pressable onPress={onAccept} style={styles.accept}><Text style={styles.acceptText}>Accept Ride</Text></Pressable></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { paddingBottom: 24 }, header: { padding: 18, paddingTop: 25, backgroundColor: colors.brand, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, greeting: { color: '#FFE7D9', fontSize: 12 }, title: { color: '#fff', fontSize: 19, fontWeight: '900', marginTop: 4 }, online: { backgroundColor: '#FF8A4C', borderRadius: 18, paddingHorizontal: 11, paddingVertical: 8, flexDirection: 'row', gap: 5 }, onlineDot: { color: '#D1FADF' }, onlineText: { color: '#fff', fontWeight: '800', fontSize: 12 }, stats: { backgroundColor: colors.brand, flexDirection: 'row', justifyContent: 'space-around', paddingBottom: 16 }, statValue: { color: '#fff', textAlign: 'center', fontSize: 16, fontWeight: '900' }, statLabel: { color: '#FFE7D9', fontSize: 11, marginTop: 3 }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '900', marginHorizontal: 18, marginTop: 17, marginBottom: 9 }, count: { color: '#fff', backgroundColor: colors.brand, paddingHorizontal: 7, borderRadius: 10, fontSize: 11 }, card: { backgroundColor: colors.surface, borderRadius: 15, borderWidth: 1, borderColor: colors.border, marginHorizontal: 18, marginBottom: 12, padding: 14 }, name: { color: colors.text, fontWeight: '800', fontSize: 15 }, meta: { color: colors.muted, fontSize: 11, marginTop: 3 }, route: { backgroundColor: '#F8F9FA', borderRadius: 10, padding: 10, gap: 8, marginVertical: 11 }, green: { color: colors.success }, orange: { color: colors.brand }, fare: { color: colors.brand, fontWeight: '900', fontSize: 17, marginBottom: 10 }, accept: { backgroundColor: colors.brand, borderRadius: 10, minHeight: 42, alignItems: 'center', justifyContent: 'center' }, acceptText: { color: '#fff', fontWeight: '800' }, empty: { alignItems: 'center', justifyContent: 'center', padding: 34, gap: 8 }, emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '800' }, muted: { color: colors.muted, fontSize: 12 }, error: { color: colors.danger, marginHorizontal: 18, fontSize: 12 } });
